/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package as;

import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dell
 */
public class Student extends javax.swing.JFrame {
    String imgpath;
    /**
     * Creates new form UI
     */
    public Student() {
        initComponents();
        setDefaultImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentimg = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        Telephone = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        searchbyname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("DOB");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel7.setText("Street");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel8.setText("City");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(0, 255, 255));
        jButton2.setText("browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 130, -1));

        studentimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(studentimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 140, 160));

        city.setText(" ");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 110, -1));

        studentid.setText(" ");
        jPanel1.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, -1));

        fname.setText(" ");
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, -1));

        lname.setText(" ");
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

        no.setText(" ");
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 110, -1));

        street.setText(" ");
        jPanel1.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 110, -1));

        email.setText(" ");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, -1));

        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        mobile.setText(" ");
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 170, -1));

        jLabel11.setText("Mobile");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        tp.setText(" ");
        jPanel1.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 170, -1));

        Telephone.setText("Telephone");
        jPanel1.add(Telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(0, 255, 255));
        jButton3.setText("Save Student");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 110, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(0, 255, 255));
        jButton4.setText("Update Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(0, 255, 255));
        jButton5.setText("Search Student by ID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 170, -1));

        searchbyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbynameActionPerformed(evt);
            }
        });
        searchbyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchbynameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbynameKeyReleased(evt);
            }
        });
        jPanel1.add(searchbyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 190, -1));

        jLabel9.setText("Search by name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Telephone", "Mobile"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 1080, 120));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(0, 255, 255));
        jButton6.setText("List all students");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(0, 255, 255));
        jButton7.setText("Print View");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 100, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(0, 255, 255));
        jButton8.setText("All student Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("Student");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 160, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Auto generate StudentID
        try{
            ResultSet rs=DB.search("select count(studentid) as x from student");
            if(rs.next()){
                int count = rs.getInt("x");
                ++count;
                Date d=new Date();
                SimpleDateFormat sdf= new SimpleDateFormat("yyyy");
                String id="ST"+sdf.format(d)+count;
                studentid.setText(id);
                //System.out.println(sdf.format.Date);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Image Browse
        try{
            JFileChooser jfc=new JFileChooser();
            int jf= jfc.showOpenDialog(this);
            System.out.print(jf);
            if (jf==jfc.APPROVE_OPTION){
                File f =jfc.getSelectedFile();
                String path=f.getAbsolutePath();
                //System.out.println(path);
                imgpath=path.replace("\\","/");
                f=new File(imgpath);
                Image img=ImageIO.read(f);
                img=img.getScaledInstance(studentimg.getWidth(), studentimg.getHeight(),Image.SCALE_SMOOTH);
                studentimg.setIcon(new ImageIcon(img));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Save Student
        try{
          Date d=jDateChooser1.getDate();
          SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
          String dob=sdf.format(d);
          DB.iud("insert into student values('"+studentid.getText()+"','"+fname.getText()+"','"+lname.getText()+"','"+dob+"','"+no.getText()+"','"+street.getText()+"','"+city.getText()+"','"+tp.getText()+"','"+mobile.getText()+"','"+email.getText()+"','"+imgpath+"')");
          clearField();
          JOptionPane.showMessageDialog(this, "Saved!");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Search by ID
        try {
            ResultSet rs=DB.search("select * from student where studentid='"+studentid.getText()+"'");
            if(rs.next()){
                fname.setText(rs.getString("fname"));
                lname.setText(rs.getString("lname"));
                jDateChooser1.setDate(rs.getDate("dob"));
                no.setText(rs.getString("no"));
                street.setText(rs.getString("street"));
                city.setText(rs.getString("city"));
                tp.setText(rs.getString("tp"));
                mobile.setText(rs.getString("mp"));
                email.setText(rs.getString("email"));
                imgpath= rs.getString("imgurl");
                File f=new File(imgpath);
                Image img=ImageIO.read(f);
                img = img.getScaledInstance(studentimg.getWidth(),studentimg.getHeight(), Image.SCALE_SMOOTH);
                studentimg.setIcon(new ImageIcon(img));
                JOptionPane.showMessageDialog(this, "Search Finished!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // update
        try{
            Date d=jDateChooser1.getDate();
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            String dob=sdf.format(d);
            DB.iud("update student set "
                    + "fname='"+fname.getText()+"',"
                    + "lname='"+lname.getText()+"',"
                    + "dob='"+dob+"',"
                    + "no='"+no.getText()+"',"
                    + "street='"+street.getText()+"',"
                    + "city='"+city.getText()+"',"
                    + "tp='"+tp.getText()+"',"
                    + "mp='"+mobile.getText()+"',"
                    + "email='"+email.getText()+"',"
                    + "imgurl='"+imgpath+"' "
                    + "where studentid='"+studentid.getText()+"'");
            clearField();
            JOptionPane.showMessageDialog(this, "Updated!");
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // search all students to table
        try{
            ResultSet rs=DB.search("select * from student");
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString("studentid"));
                v.add(rs.getString("fname"));
                v.add(rs.getString("lname"));
                v.add(rs.getString("tp"));
                v.add(rs.getString("mp"));
                dtm.addRow(v);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void searchbynameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbynameKeyReleased
        // Search by Name
        try{
            ResultSet rs= DB.search("select * from student where fname like '"+searchbyname.getText()+"%'");
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            System.out.println(rs.isFirst());
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString("studentid"));
                v.add(rs.getString("fname"));
                v.add(rs.getString("lname"));
                v.add(rs.getString("tp"));
                v.add(rs.getString("mp"));
                dtm.addRow(v);
            }
            }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchbynameKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        String id= jTable1.getValueAt(selectedRow, 0).toString();
        try{
            ResultSet rs = DB.search("select * from student where studentid='"+id+"'");
            if(rs.next()){
                studentid.setText(rs.getString("studentid"));
                fname.setText(rs.getString("fname"));
                lname.setText(rs.getString("lname"));
                jDateChooser1.setDate(rs.getDate("dob"));
                no.setText(rs.getString("no"));
                street.setText(rs.getString("street"));
                city.setText(rs.getString("city"));
                tp.setText(rs.getString("tp"));
                mobile.setText(rs.getString("mp"));
                email.setText(rs.getString("email"));
                imgpath= rs.getString("imgurl");
                File f=new File(imgpath);
                Image img=ImageIO.read(f);
                img = img.getScaledInstance(studentimg.getWidth(),studentimg.getHeight(), Image.SCALE_SMOOTH);
                studentimg.setIcon(new ImageIcon(img));
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // All student report
        try{
            String path="D:\\report.jrxml";
            JasperReport cmpr= JasperCompileManager.compileReport(path);
            JasperPrint fr= JasperFillManager.fillReport(cmpr, null, DB.getDBcon());
            JasperViewer.viewReport(fr,false);
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            try{
            String path="D:\\report1.jrxml";
            JasperReport cmpr= JasperCompileManager.compileReport(path);
            Map<String, Object> m=new HashMap<>();
            m.put("stid", studentid.getText());
            JasperPrint fr= JasperFillManager.fillReport(cmpr, m, DB.getDBcon());
            JasperViewer.viewReport(fr,false);
        } catch(Exception e){
            e.printStackTrace();
        }
            
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchbynameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbynameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbynameKeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MainPanel m=new MainPanel();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void searchbynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbynameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Telephone;
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField no;
    private javax.swing.JTextField searchbyname;
    private javax.swing.JTextField street;
    private javax.swing.JTextField studentid;
    private javax.swing.JLabel studentimg;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
void setDefaultImage(){
try{
URL resource = getClass().getResource("/img/defimg.png");
Image img = ImageIO.read(resource);
img = img.getScaledInstance(studentimg.getWidth(),studentimg.getHeight(),Image.SCALE_SMOOTH);
studentimg.setIcon(new ImageIcon(img));
}catch(Exception e){
    e.printStackTrace();
}
}

    private void clearField() {
      studentid.setText(null);
      fname.setText(null);
      lname.setText(null);
      jDateChooser1.setDate(null);
      street.setText(null);
      city.setText(null);
      tp.setText(null);
      email.setText(null);
      
    }
}
